server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        secret-key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
        username: nacos
        password: nacos
    # 网关
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  main:
    allow-bean-definition-overriding: true

knife4j:
  gateway:
    enable: true
    routes:
      - name: consumer
        url: /consumer10003/v3/api-docs?group=default
        service-name: user-service
        order: 2
      - name: provider
        url: /privoder9002/v3/api-docs?group=default
        service-name: order-service
        order: 3



