server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        secret-key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
        username: nacos
        password: nacos
    # 网关
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  main:
    allow-bean-definition-overriding: true

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services: ${spring.application.name}



